spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

server:
  port: 8080
  servlet:
    context-path: /graffiti
  error:
    include-message: always
  forward-headers-strategy: framework

  file-storage:
    application-home: true
    directory: uploads
    subdirectory-pattern: "^(.{4})(.{2})(.{2}).*$"
    whitelist:
      - image/bmp
    filename:
      unknown: (unknown)
      format: "%1$s-%2$06d.%3$s"
      randomizer-limit: 1000000
      timestamp:
        format: yyyyMMddHHmmssSSS
        time-zone: UTC
