remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Graffiti Service"
description: "Web service to manage graffiti collaboration"
author:
  name: "Cheo, Sam, Marco"

# Do not change the following line.
  copyright: true
